# Generated by Django 3.1.7 on 2021-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_winners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pointless',
        ),
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
