python -c "from test0 import test_prime; test_prime(1, False)"
python -c "from test0 import test_prime; test_prime(8, False)"
python -c "from test0 import test_prime; test_prime(3, True)"
python -c "from test0 import test_prime; test_prime(11, True)"
python -c "from test0 import test_prime; test_prime(25, False)"
python -c "from test0 import test_prime; test_prime(17, True)"